# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='お名前')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='都道府県')),
                ('episode', models.TextField(blank=True, verbose_name='エピソード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
