# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='created_at',
            new_name='created',
        ),
    ]
