# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180207_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='address',
            new_name='ken',
        ),
    ]
